version: "3.8"

services:
  bot:
    image: ghcr.io/isaacbatst/golpe-bot:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bot.rule=Host(`bot.congressosimulator.com.br`)"
      - "traefik.http.services.bot.loadbalancer.server.port=YOUR_BOT_PORT"
      - "traefik.http.routers.bot.entrypoints=websecure"
      - "traefik.http.routers.bot.tls.certresolver=myresolver"
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - traefik-public
    volumes:
      - /home/fingram-bot/database:/app/database

networks:
  traefik-public:
    external: true
