version: "3.8"

services:
  bot:
    image: ghcr.io/isaacbatst/fingram-bot:${GIT_COMMIT_HASH:-latest}
    user: "1000:1000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bot.rule=Host(`api-carteira.isaacbatst.com.br`)"
      - "traefik.http.services.bot.loadbalancer.server.port=3002"
      - "traefik.http.routers.bot.entrypoints=websecure"
      - "traefik.http.routers.bot.tls.certresolver=myresolver"
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - traefik-public
    volumes:
      - /home/fingram-bot/database:/app/database
    env_file:
      - envfile

networks:
  traefik-public:
    external: true
